### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by jbkempf**

### CODE REVIEW

**Comment by sahlberg** [comment]
Awesome!  Thanks and merged.

**Comment by jbkempf** [comment]
Great Thanks!
Now we just need to be patient and wait for the next release :D

**Comment by sahlberg** [comment]
I will try getting a new release out tomorrow or monday.

**Comment by jbkempf** [comment]
Any hope for the release, btw?

**Comment by sahlberg** [comment]
Done.

**Comment by jbkempf** [comment]
Rocks

**Pull request merged**
