### PR TITLE
Allow autoreconnect to be disabled

### PR DESCRIPTION
**Pull request by earlchew**
Signed-off-by: Earl Chew <earl_chew@yahoo.com>

### CODE REVIEW

**Comment by earlchew** [comment]
https://github.com/sahlberg/libnfs/issues/212

**Comment by sahlberg** [comment]
The patch looks fine, but I am a little curious about the use-case.
Traditionally, nfs clients default to try reconnecting forever and never giving up.

Libnfs will not retry forever, but retry reconnecting the socket 10 times. This would if the network/server is down be in the order of a few minutes, depending on how long connect() on the client takes to fail the connection attempt.
With this change libnfs will instead fail immediately and thus not be able to recover from brief network outages.

As this is controlled by the user and it defaults to not diable the 10 reconnect attempts, I am not against
adding this feature but just curious of the usecase.

If what you do want is just to have it fail much faster so that the application can try to recover maybe a better solution than the current "try 10 times, regardless how much wall-time that is" or your "dont try to recover at all" would be to be something timer based, i.e.   allow trying to reconnect until n seconds have passed and then give up.  N being user configurable.

**Comment by earlchew** [comment]
> Traditionally, nfs clients default to try reconnecting forever and never giving up.

The use case that I have is an application that uses libnfs to connect to a distributed storage cluster where there are multiple end points, and all provide a consistent view onto the stored data. In this case, there is a desire to have better control over the time to cut over from one failed connection to another.

For this scenario, re-trying a failed connection indefinitely is undesirable, and failing as-soon-as-possible allows the retry policy to be entirely in the hands of the application. This is satisfactory for the use-case that I am interested in.

> If what you do want is just to have it fail much faster so that the application can try to recover maybe a better solution than the current "try 10 times, regardless how much wall-time that is" or your "dont try to recover at all" would be to be something timer based, i.e. allow trying to reconnect until n seconds have passed and then give up. N being user configurable.

If you would like to see this to be more configurable, I think there are two possibilities:
* Allow the number of retries to be configured: zero means to fail immediately, 10 would match the current behaviour.
* Allow the duration of retries to be configured: zero means fail immediately, 100s would mean retry for at least 100s. There is no way to configure this to be the same as the 10 reconnection attempts that the current implementation provides.

**Comment by sahlberg** [comment]
See my comments in https://github.com/sahlberg/libnfs/issues/212
so that we can try doing the reconnect to a different server without dropping any PDUs in-flight and causing dataloss.


One additional thing you will need to do in order to get this to work is configuration management on your nfs server.
In order to be able to re-issue these nfs commands to the new server it is imperative that the filehandles MUST remain stable across the different servers. If they are not, the server will return -ESTALE which is a non-recoverable error :-(

If you have a cluster filesystem backing your clustered nfs servers, that cluter filesystem needs to guarantee that the inodes and filehandles are stable across the nodes in your storage cluster.
GPFS does guarantee this and can do failover between nodes completely transparently.
It also will migrate the ip addresses you access the nfs server through so you dont really need to have this "swap target socket address" support in libnfs.
I do not know how well other clusters filesystems handle this, but if they do not guarantee that filehandles are stable across the cluster, you will unfortunately have dataloss every time you do a failover due to -ESTALE (with libnfs as well as with kernel nfs client) :-(

Also make sure that you specify an explicit fsid=...  for every export in /etc/exports and have this in sync across all the server nodes so that fsid is stable as well.

**Comment by sahlberg** [comment]
Merged, thanks.

**Pull request merged**
